--- #YAML:1.0
name:                Querylet-Output-Text
version:             0.112
abstract:            output querylet results to text tables
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Querylet::Output:              0.16
    Querylet::Query:               0.28
    Test::More:                    0
    Text::Table:                   1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
